// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace MyBlogApp.Data
{
    public partial class Message
    {
        public int MessageId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }

        public string Subject { get; set; }

        public string Content { get; set; }
        public DateTime? CreationDate { get; set; }
    }
}